<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-74B2U81" failures="1" tests="10" name="Assert.Method" time="0.050" errors="0" timestamp="06 Oct 2024 06:18:03 GMT" skipped="0">
  <testcase classname="Assert.Method" name="testFail" time="0.006">
    <failure message="Exception occurred: Division by zero!" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Exception occurred: Division by zero!
	at org.testng.Assert.fail(Assert.java:93)
	at Assert.Method.testFail(Method.java:82)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="Assert.Method" name="testAssertNull" time="0.002"/>
  <testcase classname="Assert.Method" name="testAssertNotSame" time="0.001"/>
  <testcase classname="Assert.Method" name="testAssertSame" time="0.003"/>
  <testcase classname="Assert.Method" name="testAssertFalse" time="0.002"/>
  <testcase classname="Assert.Method" name="testAssertEquals" time="0.002"/>
  <testcase classname="Assert.Method" name="testAssertArrayEquals" time="0.027"/>
  <testcase classname="Assert.Method" name="testAssertNotEquals" time="0.002"/>
  <testcase classname="Assert.Method" name="testAssertTrue" time="0.003"/>
  <testcase classname="Assert.Method" name="testAssertNotNull" time="0.002"/>
</testsuite> <!-- Assert.Method -->
